name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
          
      - name: Dependencies install 
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Digital Ocean | Copy dist
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          source: ".,!node_modules"
          target: "~/app/gobarber-api"
          
      - name: Digital Ocean | Dependencies install | Migrations | Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          script: |
            cd ~/app/gobarber-api 
            npm install
            npm run typeorm migration:run
            pm2 restart gobarber-api
